import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider"
import { Navigation } from '@/components/ui/navigation';
import { ThemeSwitch } from "@/components/ui/theme-switch"

import { Back } from "@/components/ui/back"
import { Footer } from "@/components/ui/footer"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
     children: React.ReactNode;
   }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                    <div className="lg:pl-32">

                      <div className="mx-auto max-w-6xl space-y-8 px-2 pt-20 lg:px-16 lg:py-2">

                          <div class="grid  grid-cols-2">
                            <div><ThemeSwitch/></div>
                            <div><Navigation/></div>
                          </div>

                            <div className="rounded-lg bg-vc-border-gradient p-px ">
                              <div className="rounded-lg p-3.5 lg:p-6">{children}</div>
                            </div>

                          <div class="grid  grid-cols-2">
                            <div><Back/></div>
                            <div><Footer/></div>
                          </div>

                          </div>
                    </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
